name: uav
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - numpy
  - scipy
  - pandas
  - pip:
      # --- Core UAV ---
      - mavsdk==3.15.3
      - pyserial==3.5
      
      # --- UI & Async ---
      - PyQt5==5.15.11
      - PyQtWebEngine==5.15.7
      - asyncqt==0.8.0
      - qasync==0.28.0
      
      # --- AI & Vision ---
      - torch
      - torchvision
      - ultralytics==8.4.37
      - opencv-python-headless==4.13.0.92
      - imutils==0.5.4
      
      # --- Map & Geodata ---
      - branca==0.8.2
      - folium==0.20.0
      - shapely==2.1.2
      - geographiclib==2.1
      
      # --- Utilities ---
      - pygame==2.6.1
      - pyyaml==6.0.3
      - tqdm==4.67.3
      - colorlog==6.10.1
      - pyfiglet==1.0.4

      - decorator
